language: python
python:
  # - "3.6"
  # - "3.7"
  - "3.8"

# services: postgresql

# before_install:
  # - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  # - sudo service postgresql restart
  # - sleep 1
  # - postgres --version


install:
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade pytest pytest-django pytest-cov codecov mixer selenium

before_script:
  - psql -c "create database testdb;" -U travis

script:
  # - python manage.py collectstatic
  # - python manage.py migrate --run-syncdb
  - PYTHONWARNINGS=all travis_retry pytest --ds=dqmhelper.test_ci_settings --cov=. --ignore certifier/tests/test_certifier_views.py --ignore shiftleader/tests/test_shiftleaderreport.py --ignore analysis/tests/test_analysis_views.py --ignore oms/tests/test_oms_utils.py --ignore plot/tests/test_plot_views.py --ignore runregistry/tests/test_runregistry_client.py --ignore addrefrun/tests/test_addrefrun_views.py

after_success:
  - codecov
 
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      # - postgresql-server-dev-12
 
env:
  global:
    - PGUSER=travis
    - PGVER=12
    - PGPORT=5433
    # - PGHOST=localhost
